### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by mustafa-archived** [LinuxForGeeks/SilatyQt#1]
@AXeL-dev

**Comment by mustafa-archived** [comment]
This is how the app looks on all 3 platforms!

![image](https://github.com/LinuxForGeeks/SilatyQt/assets/42213155/0d84bd6e-78ac-40a7-957f-96ae345816b9)
![image](https://github.com/LinuxForGeeks/SilatyQt/assets/42213155/ff255d24-7a74-4006-af9f-ff763539aa23)
![image](https://github.com/LinuxForGeeks/SilatyQt/assets/42213155/5092e3d9-df6a-4970-83b2-3c083f0373e4)

**Comment by mustafa-archived** [comment]
if you wish to try it, you can get a build from the [Actions tab](https://github.com/LinuxForGeeks/SilatyQt/actions)

**Comment by mustafa-archived** [comment]
@AXeL-dev the app is complete, I released it https://github.com/LinuxForGeeks/SilatyQt/releases/tag/1.6

**Comment by AXeL-dev** [comment]
> This is how the app looks on all 3 platforms!
> 
> ![image](https://user-images.githubusercontent.com/42213155/240282745-0d84bd6e-78ac-40a7-957f-96ae345816b9.png) ![image](https://user-images.githubusercontent.com/42213155/240282781-ff255d24-7a74-4006-af9f-ff763539aa23.png) ![image](https://user-images.githubusercontent.com/42213155/240282816-5092e3d9-df6a-4970-83b2-3c083f0373e4.png)

Very nice & clean, good work!

**Comment by mustafa-archived** [comment]
@AXeL-dev JazakAllah akhi, I have a request, can you pin this repository to the org behind the Silaty one?
![image](https://github.com/LinuxForGeeks/SilatyQt/assets/42213155/a509a48a-a26b-4adf-a2fb-5989a73785c2)

**Comment by AXeL-dev** [comment]
Yes sure!

**Comment by mustafa-archived** [comment]
JazakAllahu Khayran
